steps:
  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v1.3.1:
        run: tests
  - wait
  - label: ":docker: :rocket:"
    command: "docker-compose build release && docker-compose push release"
    branches: master
