steps:
  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v1.3.2:
        run: tests
  - wait
  - label: ":docker: :rocket:"
    plugins:
      docker-compose#v1.3.2:
        push: release
    branches: master
