steps:
  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v1.3.1:
        run: tests
  - wait
  - label: ":docker: :rocket:"
    command: "docker-compose push release index.docker.io/buildkite/plugin-tester"
    branches: master
