steps:
  - label: ":docker: :hammer:"
    plugins:
      docker-compose#v3.4.0:
        run: tests
  - wait
  - label: ":docker: :rocket:"
    plugins:
      docker-login#v2.0.1: ~
      docker-compose#v3.4.0:
        push: release
    branches: master
